language: cpp
sudo: required
dist: bionic
compiler:
- gcc
os:
- linux
before_install:
- sudo apt-get update
- sudo apt-get install -y gcc-multilib g++-multilib
- cd .. && git clone --recurse-submodules -j8 https://github.com/alliedmodders/sourcemod
- cd .. && git clone https://github.com/alliedmodders/hl2sdk
script:
- ENGINE=csgo make
