language: cpp
sudo: required
dist: bionic
compiler:
- gcc
os:
- linux
before_install:
- sudo apt-get update
- sudo apt-get install -y gcc-multilib g++-multilib
- cd $TRAVIS_BUILD_DIR/.. && git clone --recurse-submodules -j8 https://github.com/alliedmodders/sourcemod && cd sourcemod && git checkout $SM_VERSION
- cd $TRAVIS_BUILD_DIR/.. && git clone https://github.com/alliedmodders/metamod-source.git mmsource && cd mmsource && git checkout $MM_VERSION
- cd $TRAVIS_BUILD_DIR/.. && git clone https://github.com/alliedmodders/hl2sdk
script:
- cd $TRAVIS_BUILD_DIR/../hl2sdk && git checkout $HL2SDK
- cd $TRAVIS_BUILD_DIR
- make
env:
  global:
    - MM_VERSION=1.10-dev
    - SM_VERSION=1.9-dev

  matrix:
    - ENGINE=csgo HL2SDK=csgo
    - ENGINE=left4dead2 HL2SDK=l4d2
    - ENGINE=left4dead HL2SDK=l4d
    - ENGINE=css HL2SDK=css
    - ENGINE=orangeboxvalve HL2SDK=orangebox #Not sure about these at all.
    - ENGINE=orangebox HL2SDK=sdk2013 #Not sure about these at all.
    - ENGINE=original HL2SDK=episode1 #Not sure about these at all.