language: cpp
sudo: required
dist: bionic
compiler:
- gcc
os:
- linux

before_install:
- sudo apt-get update
- sudo apt-get install -y gcc-multilib g++-multilib
- cd $TRAVIS_BUILD_DIR/.. && git clone --recurse-submodules -j8 https://github.com/alliedmodders/sourcemod && cd sourcemod && git checkout $SM_VERSION
- cd $TRAVIS_BUILD_DIR/.. && git clone https://github.com/alliedmodders/metamod-source.git mmsource && cd mmsource && git checkout $MM_VERSION
- cd $TRAVIS_BUILD_DIR/.. && git clone https://github.com/alliedmodders/hl2sdk

script:
- cd $TRAVIS_BUILD_DIR/
- ENGINE=csgo HL2SDK=csgo ./scripts/travisBuild.sh
- ENGINE=left4dead2 HL2SDK=l4d2 ./scripts/travisBuild.sh
- ENGINE=left4dead HL2SDK=l4d ./scripts/travisBuild.sh
- ENGINE=css HL2SDK=css ./scripts/travisBuild.sh
- ENGINE=original HL2SDK=episode1 ./scripts/travisBuild.sh #Not sure about this HL2SDK
# These two are broken, so lets ignore them for now...
# - ENGINE=orangeboxvalve HL2SDK=orangebox ./scripts/travisBuild.sh #Not sure about this HL2SDK
# - ENGINE=orangebox HL2SDK=sdk2013 ./scripts/travisBuild.sh #Not sure about this HL2SDK
- ls -la $TRAVIS_BUILD_DIR/Release

env:
  global:
    - MM_VERSION=1.10-dev
    - SM_VERSION=1.9-dev

before_deploy:
- cd $TRAVIS_BUILD_DIR/
- ./scripts/travisPrepareRelease.sh
- tar -czf release.tar.gz staging/*

deploy:
  provider: releases
  api_key:
    secure: OGQfi8rF4n7Z3KGEhP1K1yH4msZevDTsojm+3QkBOAM9SlBE6kVzNJM6FTkq16BnO1/ZT2qYHEmgjRhOMAVSupe1IIU05kios5xYRg3QZY8GPY+r6dsLh2AmAP1jsSkc8HDMrxKV21ti8KnC3kwXzcwxXCOsMYYqpF+W0UnQkYrPU2mcmrvOTQrRaH05+6UiCBiIdkpfghbNRLHaF6T9XHULDY65R4t96xolwpdsVKsrlpi2w4p1B3r/mZJD+s39TabB4AvGWUnZA5fxBR304u0td++2jCv7Ih5BRi0eiiK4NCXNGsJSPzqB9PW4zfZ7KaJgYNW4dTp5ORyjFDFpf5ZkUDSh27jWK5le13JRGLJviaUA4HpjypuL/WKFprYq2Vhi318sefestwPGGvWskWLVYqvpc0gWHoLsMNLD7dJmUyZC91zqb5s6lkvCLp5HHNzUpDWJxWpd3SNHF9WM1mhWNp9AheUMXc42FWdlsYVUMxRKQuovrgZFCWInCwaAe/c9ayxF7WUcud+G4fFjKLrqwvC9A6mHAD8nTpN38ZSumqu7eYnDbdtaOkJ9uS4C6Tz9/cUXGno+OF2CRysGPG986UptmCnRFlXTXkobX+4g1v799cFJNMCso7WcHmXXF05AJBErNlAvdu1UP6UFYO92UCD1HzNm1GY1vPwJduI=
  skip_cleanup: true
  file: release.tar.gz
  draft: true
  on:
    repo: walliski/Cleaner
    branch: release-binaries