language: cpp
sudo: required
dist: bionic
compiler:
- gcc
os:
- linux
before_install:
- sudo apt-get update
- sudo apt-get install -y gcc-multilib g++-multilib
- cd $TRAVIS_BUILD_DIR/.. && git clone --recurse-submodules -j8 https://github.com/alliedmodders/sourcemod
- cd $TRAVIS_BUILD_DIR/.. && git clone https://github.com/alliedmodders/hl2sdk
script:
- cd $TRAVIS_BUILD_DIR/../hl2sdk && git checkout $HL2SDK
- cd $TRAVIS_BUILD_DIR
- make
env:
  global:
    - ENGINE=csgo HL2SDK=csgo